"""Expose existing green CSS colors as theme variables; preserve semantic blues/oranges."""
from pathlib import Path
import colorsys, re
root=Path(__file__).resolve().parents[1]
colors={}
for file in ['app/styles.css','app/map/map.css']:
    path=root/file
    text=path.read_text(encoding='utf-8')
    def replace(match):
        raw=match[0][1:]
        if len(raw) not in (3,4,6,8): return match[0]
        hexcode=''.join(c*2 for c in raw) if len(raw) in (3,4) else raw
        r,g,b=[int(hexcode[i:i+2],16)/255 for i in (0,2,4)]
        h,l,s=colorsys.rgb_to_hls(r,g,b)
        if not 55<=h*360<=190 or s<.015:return match[0]
        if l>.94: rgb=(.980,.969,1.0)
        else: rgb=colorsys.hls_to_rgb(270/360,l,min(.78,s*1.4+.06))
        value='#'+''.join(f'{round(x*255):02x}' for x in rgb)+hexcode[6:]
        colors[raw]=value
        return f'var(--tone-{raw},#{raw})'
    # Already generated var fallbacks are retained on repeat runs.
    text=re.sub(r'(?<!,)#[0-9a-fA-F]{3,8}\b',replace,text)
    path.write_text(text,encoding='utf-8')
    for raw in re.findall(r'var\(--tone-([0-9a-fA-F]+),',text):
        replace(type('M',(),{'__getitem__':lambda self,k:'#'+raw})())
overrides={'173b32':'#5620ad','234a3b':'#6531b5','dbf68b':'#e5d5ff','f6f7f2':'#faf8ff'}
colors.update(overrides)
(root/'app/theme-purple.css').write_text('/* Generated by tools/prepare_theme.py */\nhtml[data-theme="purple"]{\n'+''.join(f'  --tone-{k}:{v};\n' for k,v in sorted(colors.items()))+'}\n',encoding='utf-8')
